fire_sale/fire_sale/urls.py
from django.contrib import admin
from django.urls import path, include

import fire_sale
from fire_sale import views
from fire_sale.views import permission_denied_view
from fire_sale.views import page_not_found_view
# from django.conf.urls import handler404
from django.views.defaults import page_not_found

urlpatterns = [
    path('', include('item.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('categories/', include('category.urls')),
    path('offers/', include('offer.urls')),
    path('watchlist/', include('watchlist.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + [path('404/', views.page_not_found_view)]

handler403 = permission_denied_view
# handler404 = page_not_found_view
handler404 = page_not_found_view

fire_sale/item/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    # http://localhost:8000/items
    path('', views.index, name="item-index"),
    path('<int:id>', views.get_item_details_by_id, name="item-details"),
    path('create_item', views.create_item, name="create-item"),
    path('delete_item/<int:id>', views.delete_item, name="delete-item"),
    path('edit_item/<int:id>', views.edit_item, name="edit-item"),
    path('<int:item_id>/offers', views.item_offers, name="item-offers"),
    path('<int:item_id>/offers_buyer_view', views.item_offers_buyers, name="item-offers-buyers"),
]

fire_sale/item/models.py
import django.utils.timezone
from django.db import models
from django.db.models import Q

from user.models import User
from category.models import Category
# Create your models here.


class Item(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.FloatField()
    seller = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ItemStatuses(models.Model):
    status = models.CharField(max_length=255, primary_key=True)

    def __str__(self):
        return self.status


class ItemStats(models.Model):
    views = models.IntegerField(default=0)
    status = models.ForeignKey(ItemStatuses, on_delete=models.PROTECT, default="Not sold")
    listing_date = models.DateField(null=True, blank=True, default=django.utils.timezone.now)
    sold_date = models.DateField(null=True, blank=True)
    item = models.OneToOneField(Item, on_delete=models.CASCADE, primary_key=True)



class ItemConditions(models.Model):
    condition = models.CharField(max_length=255, blank=False, primary_key=True)

    def __str__(self):
        return self.condition


class ItemDetails(models.Model):
    condition = models.ForeignKey(ItemConditions, on_delete=models.PROTECT)
    description = models.TextField(max_length=9999, blank=True)
    item_stats = models.OneToOneField(ItemStats, on_delete=models.CASCADE, primary_key=True)


class ItemImage(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    # image_url = models.ImageField(max_length=9999, blank=True)
    image = models.URLField(max_length=999, blank=True)

fire_sale/offer/models.py
from django.db import models
from item.models import Item
from user.models import User



# Create your models for "Offer" here:


class Offer(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='buyer_offers', blank=True, null=True)
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name='seller_offers')
    amount = models.FloatField()
    status = models.CharField(max_length=255, default="Pending answer")



class OfferDetails(models.Model):
    offer = models.OneToOneField(Offer, on_delete=models.CASCADE, primary_key=True)
    start_date = models.DateField()
    message = models.TextField(max_length=255)

fire_sale/item/forms/item_form.py
from django.forms import ModelForm, widgets
from django import forms
from item.models import Item, ItemDetails, ItemStats, ItemImage


class CreateItemForm(ModelForm):
    class Meta:
        model = Item
        exclude = ['id', 'seller']
        widgets = {
            'name': widgets.TextInput(attrs={'class': 'form-control'}),
            'price': widgets.NumberInput(attrs={'class': 'form-control', 'placeholder': '0'}),
            'category': widgets.Select(attrs={'class': 'form-control'})
        }


class CreateItemImageForm(ModelForm):
    class Meta:
        model = ItemImage
        fields = ['image']
        widgets = {
            'image': forms.URLInput(attrs={'class': 'form-control'})
        }



class CreateItemDetailsForm(ModelForm):
    class Meta:
        model = ItemDetails
        widgets = {
            'condition': widgets.Select(attrs={'class': 'form-control'}),
            'description': widgets.Textarea(attrs={'class': 'form-control'})
        }
        fields = ['condition', 'description']


# class EditItemForm(forms.ModelForm):
#     condition = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
#     description = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
#     images = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
#
#     class Meta:
#         model = Item
#         exclude = ['id', 'category', 'seller']
#         fields = ['name', 'price']


class EditItemForm(ModelForm):
    class Meta:
        model = Item
        exclude = ['id', 'seller']
        widgets = {
            'name': widgets.TextInput(attrs={'class': 'form-control'}),
            'price': widgets.NumberInput(attrs={'class': 'form-control'}),
            'category': widgets.Select(attrs={'class': 'form-control'})
        }


class EditItemImageForm(ModelForm):
    class Meta:
        model = ItemImage
        widgets = {
            'image': widgets.URLInput(attrs={'class': 'form-control'})
        }
        fields = ['image']


class EditItemStatsForm(ModelForm):
    class Meta:
        model = ItemStats
        widgets = {
            'status': widgets.Select(attrs={'class': 'form-control'})
        }
        fields = ['status']


class EditItemDetailsForm(ModelForm):
    class Meta:
        model = ItemDetails
        widgets = {
            'condition': widgets.Select(attrs={'class': 'form-control'}),
            'description': widgets.Textarea(attrs={'class': 'form-control'})
        }
        fields = ['condition', 'description']

fire_sale/item/views.py
# Import statements
from django.db.models import Max, Avg
from django.forms import formset_factory
from django.shortcuts import render, get_object_or_404, redirect
from rating.models import Rating
from user.models import UserProfile
from category.models import CategoryViews
from item.forms.item_form import CreateItemForm, EditItemForm, CreateItemImageForm, CreateItemDetailsForm, \
EditItemImageForm, EditItemDetailsForm
from item.models import Item, ItemImage, ItemDetails, ItemStats
from watchlist.models import WatchListItem
from item.service import ItemService
from django.contrib.auth.decorators import login_required
from offer.models import Offer
from django.shortcuts import render
from django.core.exceptions import PermissionDenied



def index(request):
    return render(request, 'home/index.html', context={
        'categories_and_items': ItemService.get_categories_and_items_by_userid(request.user.id),
    })

def get_item_details_by_id(request, id):
    """
    Retrieves and renders the details of an item by its ID.

    Args:
        request (HttpRequest): The HTTP request object.
        id (int): The ID of the item.

    Returns:
        HttpResponse: Renders the 'item/item_details.html' template with the item details and related information.

    Raises:
        Http404: If the item details or item stats do not exist.

    """
    item_details = get_object_or_404(ItemDetails.objects.select_related(
        'item_stats__item',
        'item_stats__item__category',
        'item_stats__item__seller',
        'condition',
    ), pk=id)

    item_stats = get_object_or_404(ItemStats, pk=id)
    item_stats.views += 1
    item_stats.save()

    if request.user.id:
        category_views = get_object_or_404(CategoryViews, user=request.user.id, category=item_stats.item.category)
        category_views.category_views += 1
        category_views.save()

    seller_id = item_details.item_stats.item.seller_id
    user_location = UserProfile.objects.get(user_info__user_id=seller_id).country

    try:
        user_rating = round(Rating.objects.filter(offer_id__seller=seller_id).aggregate(Avg('rating'))['rating__avg'], 1)
    except TypeError:
        user_rating = '(No ratings)'

    item = item_details.item_stats.item
    category_and_items = ItemService.get_category_and_items_by_itemid(item.category, id, request.user.id)
    item_images = ItemImage.objects.filter(item=item).select_related('item')
    watchlist_items = WatchListItem.objects.filter(item=item_details.item_stats)
    highest_price = Offer.objects.filter(item_id=id).aggregate(Max('amount'))['amount__max'] or 0


    return render(request, 'item/item_details.html', {
        'user_location': user_location,
        'user_rating' : user_rating,
        'item_details': item_details,
        'category_and_items': category_and_items,
        'item_images': item_images,
        'watchlist_items': watchlist_items,
        'in_watchlist': watchlist_items.exists(),
        'highest_price': highest_price,
    })

@login_required
def create_item(request):
    """
    Creates a new item.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: If the request method is POST and the form data is valid, redirects to the item details page of the created item.
        Otherwise, renders the 'item/create_item.html' template with the item creation forms.

    """
    CreateItemImageFormSet = formset_factory(CreateItemImageForm, extra=1, max_num=10, absolute_max=50, can_delete=True)

    if request.method == 'POST':
        item_form = CreateItemForm(data=request.POST)
        item_image_formset = CreateItemImageFormSet(data=request.POST)
        item_details_form = CreateItemDetailsForm(data=request.POST)

        if item_form.is_valid() and item_image_formset.is_valid() and item_details_form.is_valid():
            item = item_form.save(commit=False)
            item.seller_id = int(request.user.id)
            item.save()

            for form in item_image_formset:
                if form.cleaned_data.get('image'):
                    image = form.save(commit=False)
                    image.item = item
                    image.save()

            item_stats = ItemStats(item=item)
            item_stats.save()

            item_details = item_details_form.save(commit=False)
            item_details.item_stats_id = item_stats.item_id
            item_details.save()

            return redirect('item-details', item.id)
    else:
        item_form = CreateItemForm()
        item_image_formset = CreateItemImageFormSet()
        item_details_form = CreateItemDetailsForm()

    return render(request, 'item/create_item.html', {
        'item_form': item_form,
        'item_image_formset': item_image_formset,
        'item_details_form': item_details_form,
    })

@login_required
def delete_item(request, id):
    """
    Deletes an existing item.

    Args:
        request (HttpRequest): The HTTP request object.
        id (int): The ID of the item to delete.

    Returns:
        HttpResponse: Redirects to the 'my-listings' page after deleting the item.

    Raises:
        Http404: If the item does not exist or does not belong to the current user.

    """
    item = get_object_or_404(Item, pk=id)
    item.delete()
    return redirect('my-listings')

@login_required
def edit_item(request, id):
    """
    Edits an existing item.

    Args:
        request (HttpRequest): The HTTP request object.
        id (int): The ID of the item to edit.

    Returns:
        HttpResponse: If the request method is POST and the form data is valid, redirects to the item details page of the edited item.
        Otherwise, renders the 'item/edit_item.html' template with the item edit forms.

    Raises:
        PermissionDenied: If the item does not belong to the current user.
        Http404: If the item or item details do not exist.

    """
    ItemImageFormSet = formset_factory(EditItemImageForm, extra=1, max_num=10, absolute_max=50, can_delete=True)

    item_instance = get_object_or_404(Item, pk=id)
    item_image_instances = ItemImage.objects.filter(item_id=id)
    item_details_instance = get_object_or_404(ItemDetails, pk=id)

    if item_instance.seller.id != request.user.id:
            raise PermissionDenied()
    else:
        if request.method == 'POST':
            item_form = EditItemForm(data=request.POST, instance=item_instance)
            item_image_formset = ItemImageFormSet(data=request.POST)

            item_details_form = EditItemDetailsForm(data=request.POST, instance=item_details_instance)

            if item_form.is_valid() and item_image_formset.is_valid() and item_details_form.is_valid():
                item = item_form.save()

                # Update or create image instances
                for form, image_instance in zip(item_image_formset.forms, item_image_instances):
                    if form.cleaned_data.get('DELETE'):
                        image_instance.delete()
                    elif form.cleaned_data.get('image'):
                        image_instance.image_url = form.cleaned_data['image']  # Update the image URL field
                        image_instance.save()

                # Save any new images
                for form in item_image_formset.extra_forms:
                    if form.cleaned_data.get('image'):
                        image = form.save(commit=False)
                        image.item = item
                        image.save()

                item_details_form.save()

                return redirect('item-details', id)
        else:
            item_form = EditItemForm(instance=item_instance)
            item_image_formset = ItemImageFormSet(initial=[{'image': image.image} for image in item_image_instances])
            item_details_form = EditItemDetailsForm(instance=item_details_instance)

        return render(request, 'item/edit_item.html', {
            'item_form': item_form,
            'item_image_formset': item_image_formset,
            'item_details_form': item_details_form,
            'id': id,
    })

@login_required()
def item_offers(request, item_id):
    """
    Renders the offers for a specific item.

    Args:
        request (HttpRequest): The HTTP request object.
        item_id (int): The ID of the item.

    Returns:
        HttpResponse: Renders the 'offer/item_offers.html' template with the offers and the associated item.

    Raises:
        PermissionDenied: If the item does not belong to the current user.
        Http404: If the item does not exist.

    """
    offers = Offer.objects.filter(item_id=item_id).order_by('-amount')
    item = Item.objects.get(pk=item_id)
    if item.seller.id != request.user.id:
            raise PermissionDenied()
    else:
        return render(request, 'offer/item_offers.html', {
            "offers": offers,
            "item": item,
    })

@login_required
def item_offers_buyers(request, item_id):
    """
    Renders the offers for a specific item from the buyer's perspective.

    Args:
        request (HttpRequest): The HTTP request object.
        item_id (int): The ID of the item.

    Returns:
        HttpResponse: Renders the 'offer/item_offers_buyer_view.html' template with the offers and the associated item.

    Raises:
        Http404: If the item does not exist.

    """
    offers = Offer.objects.filter(item_id=item_id).order_by('-amount')
    item = Item.objects.get(pk=item_id)

    return render(request, 'offer/item_offers_buyer_view.html', {
        "offers": offers,
        "item": item,
    })

fire_sale/templates/item/create_item.html
{% extends 'base.html' %}
{% block content %}
    <h4>Create item</h4>
    <form class="form form-row" action="{% url 'create-item' %}" method="post">
        {% csrf_token %}
        {{ item_form.as_p }}

        {{ item_details_form.as_p }}

        <!-- Render formset -->
        <div id="formset-container">
            {{ item_image_formset.management_form }} <!-- Include formset management fields here -->
            {% for form in item_image_formset %}
                {{ form.as_table }}
            {% endfor %}
        </div>

        <div id="form-template">
            {{ item_image_formset.empty_form }}
        </div>

        <div id="add-image-button-div">
            <button type="button" id="add-image-button" class="btn btn-secondary">Add Image</button>
        </div>

        <div class="form-submit-button-container">
            <input type="submit" value="Create" class="btn btn-primary"/>
        </div>
    </form>

{% endblock %}

fire_sale/templates/item/edit_item.html
{% extends 'base.html' %}
{% block content %}
    <br>
    <h4>Edit item</h4>
    <form class="form form-row" action="{% url 'edit-item' id %}" method="post">
        {% csrf_token %}
        {{ item_form }}
        {{ item_details_form }}

        <!-- Render formset -->
        <div id="formset-container">
            {{ item_image_formset.management_form }} <!-- Include formset management fields here -->
            {% for form in item_image_formset %}
                {{ form.as_table }}
            {% endfor %}
        </div>
        
        <div id="form-template">
            {{ item_image_formset.empty_form }}
        </div>

        <div id="add-image-button-div">
            <button type="button" id="add-image-button" class="btn btn-secondary">Add Image</button>
        </div>
        
        <div class="form-submit-button-container">
            <input type="submit" value="Save" class="btn btn-primary"/>
        </div>
    </form>
{% endblock %}

fire_sale/templates/item/item_card.html
<div class="card small-item-card mx-2" data-fs-item-id="{{ item.id }}">
    <div>
        <a href="{% url 'item-details' item.id %}">
            {% if item.itemimage_set.all.0.image %}
                <img class="card-img-top" src="{{ item.itemimage_set.all.0.image }}" alt="Image for '{{ item.name }}'">
            {% else %}
                <div class="card-img-top item-img-missing"><span class="material-symbols-outlined">image</span></div>
            {% endif %}
        </a>
    </div>
    <div class="card-body">
        <a class="card-info" href="{% url 'item-details' item.id %}">
            <h5 class="card-title">{{ item.name|truncatechars:14 }}</h5>
            <p class="card-text">
                $ {{ item.price }}
                <a href="#" class="btn rounded-circle d-flex align-items-center material-symbols-outlined card-heart {% if item.is_in_watchlist %}card-heart-filled{% endif %}" title="Add item to watchlist.">
                    favorite
                </a>
            </p>
        </a>
    </div>
</div>

fire_sale/templates/item/item_details.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <script src="{% static 'js/relode.js' %}"></script>

    <div class="row">
        <div class="col-lg-1"></div>

        <div class="col-lg-9 d-flex flex-nowrap">
            <div class="d-flex flex-column">
                {% include 'item/item_image_carousel.html' %}

                <div class="item-details-info">
                    <div class="item-details-line">
                        <span class="material-symbols-outlined">visibility</span> <span>: {{ item_details.item_stats.views }}</span>
                    </div>
                    <div class="item-details-line">
                        <span class="material-symbols-outlined">favorite</span> <span>: {{ watchlist_items.count }}</span>
                    </div>
                    <div class="item-details-line">
                        <span class="material-symbols-outlined">info</span> <span>: {{ item_details.item_stats.status }}</span>
                    </div>
                    <div class="item-details-line">
                        <span class="material-symbols-outlined">new_releases</span> <span>: {{ item_details.condition }}</span>
                    </div>
                </div>
            </div>

            <div id="main-item-info-container">
                <h1>{{ item_details.item_stats.item.name }}</h1>
                <h3>Price: ${{ item_details.item_stats.item.price }}</h3>
                <h4>Highest Offer: ${{ highest_price }}</h4>
                {% if request.user.id == item_details.item_stats.item.seller_id %}
                     <a href="{% url 'item-offers' item_details.item_stats.item.id %}" class="bid-count">[{{ item_details.item_stats.item.offer_set.count }} offers]</a>
                {% else %}
                    <a href="{% url 'item-offers-buyers' item_details.item_stats.item.id %}" class="bid-count">[{{ item_details.item_stats.item.offer_set.count }} offers]</a>
                {% endif %}
                <div class="space-item"></div>
                {% if request.user.id == item_details.item_stats.item.seller_id %}
                    <a href="{% url 'delete-item' item_details.item_stats.item.id %}" class="block btn btn-primary">Delete item</a>
                    <a href="{% url 'edit-item' item_details.item_stats.item.id %}" class="block btn btn-primary">Edit item</a>
                {% else %}
                    <div id="item-details-btn">
                    {% if request.user.id %}
                        {% if item_details.item_stats.status_id != "Sold" %}
                            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#offerModal" data-itemid="{{ item_details.item_stats.item.id }}">Send an offer</button>
                        {% endif %}
                        {% if in_watchlist %}
                            <a href="{% url 'delete_from_watchlist' item_details.item_stats.item.id %}" class="btn btn-outline-primary">Remove from Watchlist</a>
                        {% else %}
                            <form method="POST" action="{% url 'add_to_watchlist' item_details.item_stats.item.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-outline-primary">Add to watchlist</button>
                            </form>
                        {% endif %}
                    {% else %}
{#                        If Guest user #}
                        {% if item_details.item_stats.status_id != "Sold" %}
                            <form method="POST" action="{% url 'login' %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Send an offer</button>
                            </form>
                            <form method="POST" action="{% url 'login' %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-outline-primary">Add to watchlist</button>
                            </form>
                        {% endif %}
                    {% endif %}
                    </div>
                {% endif %}

                <div class="item-description">
                    <h6>Description:</h6>
                    <p>{{ item_details.description }}</p>
                </div>
            </div>

        </div>
        <div class="col-lg-2 border-start border-secondary-subtle">
            <div id="seller-info">
                <h4>Seller information</h4>
                <p>Name: {{ item_details.item_stats.item.seller.full_name }}</p>
                <p>Rating: {{ user_rating }}</p>
                <p>Location: {{ user_location}}</p>
            </div>
        </div>

        

        <div class="modal fade" id="offerModal" tabindex="-1" aria-labelledby="offerModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="offerModalLabel">Send an Offer</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <!-- Your form will be loaded here via AJAX -->
                    </div>
                </div>
            </div>
        </div>

    </div>

    {% with category_and_items as category %}
        {% include 'category/category_row.html' %}
    {% endwith %}


    {% block extra_js %}
        <script src="{% static 'js/offers.js' %}"></script>
    {% endblock %}

{% endblock %}

fire_sale/templates/item/item_image_carousel.html
<div id="main-image-container" class="carousel slide">
    {% if item_images %}
        {% if item_images|length > 1 %}
            <div class="carousel-indicators">
                {% for image in item_images %}
                    <button type="button" data-bs-target="#main-image-container" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></button>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#main-image-container" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon material-symbols-outlined" aria-hidden="true">
                    arrow_back_ios
                </span>
                <span class="visually-hidden">Previous</span>
            </a>
            <a class="carousel-control-next" href="#main-image-container" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon material-symbols-outlined" aria-hidden="true">
                    arrow_forward_ios</span>
                <span class="visually-hidden">Next</span>
            </a>
        {% endif %}
        <div class="carousel-inner bg-body-secondary">
            {% for image in item_images %}
                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                    <img src="{{ image.image }}" alt="Image {{ forloop.counter1 }}">
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="item-img-missing"><span class="material-symbols-outlined">image</span></div>
    {% endif %}
</div>